### PR TITLE
Addressing potential recursive calling and added an optional has_site_visit

### PR DESCRIPTION
**Pull request by peterphilips**

### CODE REVIEW

**Review by nicholascar — CHANGES_REQUESTED** [review]
As per my comment above

**Comment by peterphilips** [comment]
@nicholascar I see, okay will address that now - thanks for picking that up!

**Comment by peterphilips** [comment]
@nicholascar just a bit confused regarding the 'has site visit' here https://w3id.org/tern/ontologies/tern/Sampling on the sampling page

**Comment by peterphilips** [comment]
Am I correct in thinking that a sampling can have a has_site_visit property (according to: https://w3id.org/tern/ontologies/tern/Sampling) in which that has_site_visit property has to have an arbitrary time (prov:startedAtTime). That has_site_visit property allows the samplings to then all link to a site by using the same has_site_visit property?

**Comment by peterphilips** [comment]
@nicholascar please refer to 39e04a280340c7a4437b034c4068480c0447f0fc and 60ce71a1d54ef02bf9aa4b7a117506f15f957ed3

**Pull request closed without merging**
